version: "3.9"

services:

  client:
    restart: 'always'
    build: ./client
    
    ports:
      - "8080:8080"

    volumes:
      - ./client

  database:
    restart: always
    build: ./bin/postgres

    ports:
      - "5432:5432"

    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}

    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init/docker-entrypoint-initdb.d

  server:
    restart: 'always'
    build: ./server

    ports:
      - "5000:5000"

    volumes:
      - ./server

    environment:
      PRISMA_DATABASE_URL: ${PRISMA_DATABASE_URL}
      
volumes:
  db-data:
    driver: local